cordova plugin add cordova-plugin-device
cordova plugin add ionic-plugin-keyboard
cordova plugin add cordova-plugin-splashscreen
cordova plugin add cordova-plugin-statusbar
cordova plugin add cordova-plugin-whitelist
cordova plugin add cordova-plugin-crosswalk-webview
cordova plugin add cordova-plugin-fcm
cordova plugin add cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-media
cordova plugin add cordova-plugin-velda-devicefeedback
cordova plugin add cordova-plugin-file-transfer
