cordova plugin rm cordova-plugin-crosswalk-webview
cordova plugin rm cordova-plugin-device
cordova plugin rm cordova-plugin-fcm
cordova plugin rm cordova-plugin-media
cordova plugin rm cordova-plugin-file-transfer
cordova plugin rm cordova-plugin-inappbrowser
cordova plugin rm cordova-plugin-splashscreen
cordova plugin rm cordova-plugin-statusbar
cordova plugin rm cordova-plugin-velda-devicefeedback
cordova plugin rm cordova-plugin-whitelist
cordova plugin rm ionic-plugin-keyboard
